require("plugins-config.treesitter")
-- require("plugins-config.catppuccin")
require("plugins-config.telescope")
require("plugins-config.lualine")
require("plugins-config.autopairs")
require("plugins-config.lsp")
require("plugins-config.presence")
require("plugins-config.copilot")
require("plugins-config.bufferline")
